showfontsadder= function(){
  sysfonts::font_add("Edgecutting","EdgecuttingLiteMedium.ttf")
  sysfonts::font_add("Sagona Book","SAGONABOOK.TTF")
  sysfonts::font_add("Sagona Book Bold","SAGONABOOKBOLD.TTF")
  sysfonts::font_add("Yuji","YujiSyuku-Regular.ttf")
  sysfonts::font_add("Bookerly","Bookerly.ttf")
  font_add("Quadrata","friz-quadrata-regular-os-5870333951e7c.ttf")
  font_add("Bruno Ace SC","BrunoAceSC-Regular.ttf")
  font_add("Righteous","Righteous-Regular.ttf")
  font_add("Verlag Book","Verlag-Book.otf")
  font_add("Helvetica","Helvetica.ttf")
  font_add("good times","good times rg.otf")
  font_add("Verlag Black","Verlag-Black.ttf")
  font_add("Cutive","CutiveMono-Regular.ttf")
  font_add("Austral Blur Light","Austral-Slab_Blur-Light.otf")
  font_add("Austral Blur Regular","Austral-Slab_Blur-Regular.otf")
  font_add("Vactory","VactorySansRegular-drrAV.ttf")
  font_add("Requin","Requiner-6RRLM.otf")
  font_add("Caviar Dreams Bold","CaviarDreams_Bold.ttf")
  font_add("Drogo","Drogowskaz.otf")
  font_add("Brigade","LightBrigade-j5zR.otf")
  font_add("Castoro","CastoroTitling-Regular.ttf")
  font_add("Libre","LibreBodoni-Regular.otf")
  font_add("Streamster","Streamster-2mBv.ttf")
  font_add("Grotesque","MDGROTESQUE-Regular.ttf")
  font_add("Alkia","Alkia.ttf")
  font_add("Vieira","Vieira.ttf")
  font_add("Menlo","Menlo-Regular.ttf")
  font_add("Samsung","samsungsharpsans-medium.otf")
  font_add_google("EB Garamond","EB Garamond")
  font_add_google("Josefin Slab","Josefin")
  font_add_google("Gruppo","Gruppo")
  font_add_google("Cinzel","Cinzel")
  font_add_google("Arapey","Arapey")
  font_add_google("Chakra Petch","Chakra")
  font_add_google("Overpass","Overpass")
  font_add_google("Coda","Coda")
  font_add_google("Yuji Syuku","Yuji")
  font_add_google("Signika","Signika",regular.wt = 400,bold.wt = 700)
}
